bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: IRkfuBf2FeH+IhHSdNzdWOS4FcGUvRn1qntL7sqEq99nqp8tvdjqIbPSeZ3MyKZcoR85SRFxfulU1uFn6rXW4vD+1ChXyrWM1JjtrtUdo7wxqGGyjK+T1HO3/1jbhhWsnY6agSjkuHNouhD3q9ytmC0wQo3sFlEJaNakJV7CreX1y7odrEajeHJfKgW3ISue21vSDYQIrJCYh1Ct2nExPOT07H+4+8d1hnAT6lpGDcMDoVOeWPxCiWpduK9PQs00g3ZN7kOxCZTDLZhIuwtdLv+rc4jsZZDDttC1EOp7SYcJ1bPKjqTDvHokeOYCqL/Edwd2N/QwWsc4zRWXnmC45zlO7OIQugwNaB6xYmkSz1YlWodaUGKgAuHP24faDt3YjdD1d+rM4rE7eWnj9FGno5qCjZc9pqIvbqbZXEDnj+onh/npFWxa3OCvUT6kbLvl/pl490WP1JNOQfrVwlHTtGUSIwDuWDXta6CjquxNnGssTTliKZikG8u5VJ4eiOBbwCnp2Hb4GTPOFAXMfLm1iFTjfBRyq62wIrmDyxUw2qJJG7dWXaRAYGyVOeU/tyv9geEd9lZBEuYBRJ5NkH9CrhuLQW1Qm73r6X2q2RmkIEIliMb/8eYlQRAAaQmcjVw6OpLBwKPSTQfs2Gpo52rwv4vjfJtyE7xmnlqd1GPO6Bw=
conda_forge_output_validation: true
